"""alter user skills

Revision ID: 06a9cb27158b
Revises: 8056d55181a5
Create Date: 2026-05-23 13:29:55.754589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a9cb27158b'
down_revision: Union[str, Sequence[str], None] = '8056d55181a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("""UPDATE user_skills us
                  SET user_id = ul.user_id
                  FROM user_levels ul
                  WHERE us.user_level_id = ul.id;"""
               )
    op.create_check_constraint("skill_user_not_null", "user_skills", "user_id IS NOT NULL")
    op.add_column('user_skills', sa.Column('profile_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_skills', 'profile_levels', ['profile_level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_column('user_skills', 'profile_level_id')
    op.drop_column('user_skills', 'user_id')
    # ### end Alembic commands ###
