"""Change profiles schema

Revision ID: 7f281c30f5f7
Revises: 1ef4bd530ff0
Create Date: 2026-03-20 14:56:54.448772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f281c30f5f7'
down_revision: Union[str, Sequence[str], None] = '1ef4bd530ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('profile_levels', sa.Column('level', sa.String(), nullable=False))
    op.drop_constraint(op.f('unq_profile_level'), 'profile_levels', type_='unique')
    op.execute(
        "ALTER TABLE profile_levels DROP CONSTRAINT profile_levels_profile_id_fkey CASCADE"
    )
    op.execute(
        "ALTER TABLE profile_levels DROP CONSTRAINT profile_levels_level_id_fkey CASCADE"
    )
    op.drop_table("levels")
    # op.drop_constraint(op.f('profile_levels_profile_id_fkey'), 'profile_levels', type_='foreignkey', cascade=True)
    # op.drop_constraint(op.f('profile_levels_level_id_fkey'), 'profile_levels', type_='foreignkey')
    op.create_foreign_key(None, 'profile_levels', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profile_levels', 'level_id')
    op.add_column('profiles', sa.Column('title', sa.String(), nullable=False, server_default="Программист"))
    op.add_column('profiles', sa.Column('description', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['title'])
    op.drop_column('profiles', 'position')
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_profile_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'profile_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_profile_id_fkey'), 'users', 'profile_levels', ['profile_level_id'], ['id'])
    op.drop_column('users', 'profile_id')
    op.drop_column('users', 'position')
    op.add_column('profiles', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'description')
    op.drop_column('profiles', 'title')
    op.add_column('profile_levels', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profile_levels', type_='foreignkey')
    op.create_foreign_key(op.f('profile_levels_level_id_fkey'), 'profile_levels', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(op.f('profile_levels_profile_id_fkey'), 'profile_levels', 'profiles', ['profile_id'], ['id'])
    op.create_unique_constraint(op.f('unq_profile_level'), 'profile_levels', ['profile_id', 'level_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('profile_levels', 'level')
    op.create_table('levels',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('levels_pkey')),
    sa.UniqueConstraint('name', name=op.f('levels_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
