"""add unq contraint questions

Revision ID: 607cf38535d2
Revises: a41d5a22c5ba
Create Date: 2026-04-06 04:14:47.541549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607cf38535d2'
down_revision: Union[str, Sequence[str], None] = 'a41d5a22c5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_unq_constraint', 'stage_questions', ['stage_id', 'num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_unq_constraint', 'stage_questions', type_='unique')
    # ### end Alembic commands ###
