"""Add profile levels

Revision ID: 1ef4bd530ff0
Revises: fe783f5e3944
Create Date: 2026-03-11 14:06:22.086969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef4bd530ff0'
down_revision: Union[str, Sequence[str], None] = 'fe783f5e3944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile_levels',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'level_id', name='unq_profile_level')
    )
    op.execute("DROP TABLE positions CASCADE")
    op.add_column('profiles', sa.Column('position', sa.String(), nullable=False))
    op.drop_column('profiles', 'position_level')
    op.drop_column('profiles', 'position_id')
    op.add_column('users', sa.Column('profile_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key('users_profile_id_fkey', 'users', 'profile_levels', ['profile_level_id'], ['id'])
    op.drop_column('users', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('users_profile_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_position_id_fkey'), 'users', 'positions', ['position_id'], ['id'])
    op.drop_column('users', 'profile_level_id')
    op.add_column('profiles', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('position_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('profiles_position_id_fkey'), 'profiles', 'positions', ['position_id'], ['id'])
    op.drop_column('profiles', 'position')
    op.create_table('positions',
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey'))
    )
    op.drop_table('profile_levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
