"""add skill_stages constraint

Revision ID: 795a1f631342
Revises: 6efa4ef734f2
Create Date: 2026-04-02 06:42:37.668444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795a1f631342'
down_revision: Union[str, Sequence[str], None] = '6efa4ef734f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stage_unq_constraint', 'skill_stages', ['skill_id', 'confirmation_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stage_unq_constraint', 'skill_stages', type_='unique')
    # ### end Alembic commands ###
