"""drop column creator_id

Revision ID: e18379849365
Revises: 607cf38535d2
Create Date: 2026-04-20 06:58:04.370265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18379849365'
down_revision: Union[str, Sequence[str], None] = '607cf38535d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skill_stages_creator_id_fkey'), 'skill_stages', type_='foreignkey')
    op.drop_column('skill_stages', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_stages', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('skill_stages_creator_id_fkey'), 'skill_stages', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
