"""alter table Questions

Revision ID: a41d5a22c5ba
Revises: 795a1f631342
Create Date: 2026-04-03 04:27:46.696351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41d5a22c5ba'
down_revision: Union[str, Sequence[str], None] = '795a1f631342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stage_questions_stage_id_fkey'), 'stage_questions', type_='foreignkey')
    op.create_foreign_key(None, 'stage_questions', 'skill_stages', ['stage_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage_questions', type_='foreignkey')
    op.create_foreign_key(op.f('stage_questions_stage_id_fkey'), 'stage_questions', 'skill_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###
