"""alter deaprtments

Revision ID: 22b69ba5f08a
Revises: 63f8b715b69a
Create Date: 2026-05-19 09:28:56.945059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b69ba5f08a'
down_revision: Union[str, Sequence[str], None] = '63f8b715b69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('divisions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user_stages', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_stages', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stages', type_='foreignkey')
    op.drop_column('user_stages', 'updated_by')
    op.drop_column('divisions', 'description')
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###
