"""add message column to events

Revision ID: 2518c3643d05
Revises: c0b6357a3629
Create Date: 2026-05-24 16:30:02.235606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2518c3643d05'
down_revision: Union[str, Sequence[str], None] = 'c0b6357a3629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'message')
    # ### end Alembic commands ###
