"""alter table profile_level

Revision ID: 2cdf26aaee95
Revises: f23c7b8099b8
Create Date: 2026-05-03 12:14:43.949281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdf26aaee95'
down_revision: Union[str, Sequence[str], None] = 'f23c7b8099b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profile_levels", "is_active", server_default=sa.text("true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
