"""add deparment_id column to profiles

Revision ID: 3ee5c19fc1c7
Revises: f0dd1ba1c5cb
Create Date: 2026-05-09 17:57:29.453204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee5c19fc1c7'
down_revision: Union[str, Sequence[str], None] = 'f0dd1ba1c5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'department_id')
    # ### end Alembic commands ###
