"""add unq constraint to profiles

Revision ID: 47ef8d99d26e
Revises: 06a9cb27158b
Create Date: 2026-05-24 11:19:18.954092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ef8d99d26e'
down_revision: Union[str, Sequence[str], None] = '06a9cb27158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'level_skills', ['profile_level_id', 'skill_id'])
    op.create_unique_constraint(None, 'profile_levels', ['profile_id', 'level_name'])
    op.create_unique_constraint(None, 'profile_levels', ['profile_id', 'num'])
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'profile_levels', type_='unique')
    op.drop_constraint(None, 'profile_levels', type_='unique')
    op.drop_constraint(None, 'level_skills', type_='unique')
    # ### end Alembic commands ###
