"""alter user_stages

Revision ID: 59badc589d71
Revises: e4d9ac19bb28
Create Date: 2026-05-17 07:41:42.704451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59badc589d71'
down_revision: Union[str, Sequence[str], None] = 'e4d9ac19bb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'user_stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user_levels', ['user_id', 'profile_level_id'])
    op.create_unique_constraint(None, 'user_profiles', ['user_id', 'profile_id'])
    op.create_unique_constraint(None, 'user_skills', ['user_level_id', 'skill_id'])
    op.create_unique_constraint(None, 'user_stages', ['user_skill_id', 'stage_version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stages', type_='unique')
    op.drop_constraint(None, 'user_skills', type_='unique')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_constraint(None, 'user_levels', type_='unique')
    op.alter_column('meetings', 'user_stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
