"""drop profile levels

Revision ID: 60f750625507
Revises: a70e629d0aac
Create Date: 2026-05-14 09:21:57.796844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60f750625507'
down_revision: Union[str, Sequence[str], None] = 'a70e629d0aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("level_skills_skill_id_fkey"), "level_skills", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("level_skills_profile_level_version_id_fkey"),
        "level_skills",
        type_="foreignkey",
    )
    op.drop_column("level_skills", "profile_level_version_id")
    op.drop_constraint(
        op.f("user_levels_profile_level_version_id_fkey"),
        "user_levels",
        type_="foreignkey",
    )

    op.execute('DROP TABLE profile_level_versions CASCADE')
    op.execute('DROP TABLE user_answers CASCADE')
    op.add_column('level_skills', sa.Column('profile_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'level_skills', 'profile_levels', ['profile_level_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'level_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_levels', 'profile_levels', ['profile_level_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.create_foreign_key(op.f('user_levels_profile_level_version_id_fkey'), 'user_levels', 'profile_level_versions', ['profile_level_version_id'], ['id'])
    op.add_column('level_skills', sa.Column('profile_level_version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'level_skills', type_='foreignkey')
    op.drop_constraint(None, 'level_skills', type_='foreignkey')
    op.create_foreign_key(op.f('level_skills_profile_level_version_id_fkey'), 'level_skills', 'profile_level_versions', ['profile_level_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('level_skills_skill_id_fkey'), 'level_skills', 'skills', ['skill_id'], ['id'])
    op.drop_column('level_skills', 'profile_level_id')
    op.create_table('user_answers',
    sa.Column('user_stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_accepted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['stage_questions.id'], name=op.f('user_answers_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_stage_id'], ['user_stages.id'], name=op.f('user_answers_user_stage_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_answers_pkey'))
    )
    op.create_table('profile_level_versions',
    sa.Column('profile_level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_level_id'], ['profile_levels.id'], name=op.f('profile_level_versions_profile_level_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_level_versions_pkey')),
    sa.UniqueConstraint('profile_level_id', 'version', name=op.f('profile_level_versions_profile_level_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
