"""add columns is_approved to meetings

Revision ID: 6633387c92d9
Revises: f2712f21505a
Create Date: 2026-05-30 16:07:37.776629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6633387c92d9'
down_revision: Union[str, Sequence[str], None] = 'f2712f21505a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.execute("""
            UPDATE meetings set is_approved = true
                WHERE user_stage_id in (
                SELECT user_stage_id
                FROM  meetings m 
                JOIN user_stages us on us.id = m.user_stage_id 
                WHERE us.updated_at > m.started_at 
            ) 
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'is_approved')
    # ### end Alembic commands ###
