"""alter user_profiles table

Revision ID: 8056d55181a5
Revises: 973b7b35f5d5
Create Date: 2026-05-23 12:51:02.923729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8056d55181a5'
down_revision: Union[str, Sequence[str], None] = '973b7b35f5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'access_scope',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('user_profiles_user_id_profile_id_key'), 'user_profiles', type_='unique')
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.create_unique_constraint(op.f('user_profiles_user_id_profile_id_key'), 'user_profiles', ['user_id', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'access_scope',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
