"""alter table stage_versions

Revision ID: 85d8e878ed32
Revises: 9e140ca7e514
Create Date: 2026-05-04 06:44:34.613444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d8e878ed32'
down_revision: Union[str, Sequence[str], None] = '9e140ca7e514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('skill_category_unq_constraint', 'skill_categories', ['skill_id', 'category_id'])
    op.drop_column('stage_versions', 'version')
    op.add_column('stage_versions', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skill_category_unq_constraint', 'skill_categories', type_='unique')
    # ### end Alembic commands ###
