"""add divisions

Revision ID: 8c164b5cba9f
Revises: deb9743a9e17
Create Date: 2026-05-12 05:17:28.738861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c164b5cba9f'
down_revision: Union[str, Sequence[str], None] = 'deb9743a9e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('division_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division_name')
    )
    op.create_table('department_profiles',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'profile_id')
    )
    op.add_column('departments', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'divisions', ['division_id'], ['id'])
    op.add_column('users', sa.Column('managed_department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('managed_division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'divisions', ['managed_division_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['managed_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'managed_division_id')
    op.drop_column('users', 'managed_department_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'division_id')
    op.drop_table('department_profiles')
    op.drop_table('divisions')
    # ### end Alembic commands ###
