"""alter events drop column

Revision ID: 973b7b35f5d5
Revises: 7b58c6cf161c
Create Date: 2026-05-22 12:08:00.445553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973b7b35f5d5'
down_revision: Union[str, Sequence[str], None] = '7b58c6cf161c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('access_scope', sa.String(), nullable=True))
    op.execute("UPDATE events set access_scope = 'Admin'")
    op.create_check_constraint("event_access_not_null", 'events', 'access_scope IS NOT NULL')

    op.drop_column('events', 'actor_role')
    op.drop_column('events', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('actor_role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'access_scope')
    # ### end Alembic commands ###
