"""add unique constrain to skill.title

Revision ID: 9b56561e9e08
Revises: a6fcf212d2ca
Create Date: 2026-05-10 11:41:41.742688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b56561e9e08'
down_revision: Union[str, Sequence[str], None] = 'a6fcf212d2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'skills', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    # ### end Alembic commands ###
