"""creage table department_users

Revision ID: 9c641c01ba58
Revises: cde9abaa47f5
Create Date: 2026-05-29 16:01:20.097500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '9c641c01ba58'
down_revision: Union[str, Sequence[str], None] = 'cde9abaa47f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_users',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'SUPERVISOR', name='departmentrole'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    op.create_index('department_user_idx', 'department_users', ['department_id', 'user_id'], unique=False)
    op.create_index('unq_department_supervisor', 'department_users', ['department_id'], unique=True, postgresql_where=sa.text("role = 'SUPERVISOR'"))
    op.execute(text("""
    INSERT INTO department_users (user_id, department_id, role)
    SELECT
        u.id,
        u.department_id,
        CASE
            WHEN d.supervisor_id = u.id THEN 'SUPERVISOR'::departmentrole
            ELSE 'EMPLOYEE'::departmentrole
        END AS role
    FROM users u
    LEFT JOIN departments d
        ON d.id = u.department_id
    WHERE u.department_id IS NOT NULL;
    """))
    op.drop_constraint(op.f('departments_supervisor_id_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_supervisor_id_fkey'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'supervisor_id')
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('departments', sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('departments_supervisor_id_fkey'), 'departments', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('departments_supervisor_id_key'), 'departments', ['supervisor_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('unq_department_supervisor', table_name='department_users', postgresql_where=sa.text("role = 'Supervisor'"))
    op.drop_index('department_user_idx', table_name='department_users')
    op.drop_table('department_users')
    # ### end Alembic commands ###
