"""drop column creator_id

Revision ID: a6fcf212d2ca
Revises: 3ee5c19fc1c7
Create Date: 2026-05-10 11:33:07.250307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fcf212d2ca'
down_revision: Union[str, Sequence[str], None] = '3ee5c19fc1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skills_creator_id_fkey'), 'skills', type_='foreignkey')
    op.drop_column('skills', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('skills_creator_id_fkey'), 'skills', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
