"""alter profiles drop columns department_id

Revision ID: a70e629d0aac
Revises: 8c164b5cba9f
Create Date: 2026-05-12 16:25:49.341905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70e629d0aac'
down_revision: Union[str, Sequence[str], None] = '8c164b5cba9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_division_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'divisions', ['division_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('profiles_department_id_fkey'), 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('profiles_department_id_fkey'), 'profiles', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_division_id_fkey'), 'departments', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###
