"""drop user_level_id column

Revision ID: c0b6357a3629
Revises: cd9c8720d96d
Create Date: 2026-05-24 14:50:18.266117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b6357a3629'
down_revision: Union[str, Sequence[str], None] = 'cd9c8720d96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_skills_user_level_id_skill_id_key'), 'user_skills', type_='unique')
    op.create_unique_constraint(None, 'user_skills', ['user_id', 'skill_id'])
    op.drop_constraint(op.f('user_skills_user_level_id_fkey'), 'user_skills', type_='foreignkey')
    op.drop_column('user_skills', 'user_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('user_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_skills_user_level_id_fkey'), 'user_skills', 'user_levels', ['user_level_id'], ['id'])
    op.drop_constraint(None, 'user_skills', type_='unique')
    op.create_unique_constraint(op.f('user_skills_user_level_id_skill_id_key'), 'user_skills', ['user_level_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
