"""update department relations

Revision ID: c1cf01f2fa2a
Revises: 22b69ba5f08a
Create Date: 2026-05-20 19:09:55.169483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cf01f2fa2a'
down_revision: Union[str, Sequence[str], None] = '22b69ba5f08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'departments', ['supervisor_id'])
    op.create_foreign_key(None, 'departments', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')
    op.add_column('divisions', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'divisions', ['supervisor_id'])
    op.create_foreign_key(None, 'divisions', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_managed_division_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_managed_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'managed_division_id')
    op.drop_column('users', 'managed_department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('managed_department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('managed_division_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_managed_department_id_fkey'), 'users', 'departments', ['managed_department_id'], ['id'])
    op.create_foreign_key(op.f('users_managed_division_id_fkey'), 'users', 'divisions', ['managed_division_id'], ['id'])
    op.drop_constraint(None, 'divisions', type_='foreignkey')
    op.drop_constraint(None, 'divisions', type_='unique')
    op.drop_column('divisions', 'supervisor_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'supervisor_id')
    # ### end Alembic commands ###
