"""alter departments fk

Revision ID: cd9c8720d96d
Revises: 47ef8d99d26e
Create Date: 2026-05-24 11:52:34.523840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9c8720d96d'
down_revision: Union[str, Sequence[str], None] = '47ef8d99d26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('department_profiles_department_id_fkey'), 'department_profiles', type_='foreignkey')
    op.drop_constraint(op.f('department_profiles_profile_id_fkey'), 'department_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'department_profiles', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'department_profiles', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department_profiles', type_='foreignkey')
    op.drop_constraint(None, 'department_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('department_profiles_profile_id_fkey'), 'department_profiles', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(op.f('department_profiles_department_id_fkey'), 'department_profiles', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
