"""alter user skills

Revision ID: cde9abaa47f5
Revises: d0ba9e8ee8a3
Create Date: 2026-05-28 03:06:04.697981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde9abaa47f5'
down_revision: Union[str, Sequence[str], None] = 'd0ba9e8ee8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_skills_profile_level_id_fkey'), 'user_skills', type_='foreignkey')
    op.drop_column('user_skills', 'profile_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('profile_level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_skills_profile_level_id_fkey'), 'user_skills', 'profile_levels', ['profile_level_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
