"""alter skill_category table

Revision ID: d0ba9e8ee8a3
Revises: 2518c3643d05
Create Date: 2026-05-26 10:18:19.550359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ba9e8ee8a3'
down_revision: Union[str, Sequence[str], None] = '2518c3643d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skill_categories_skill_id_fkey'), 'skill_categories', type_='foreignkey')
    op.drop_constraint(op.f('skill_categories_category_id_fkey'), 'skill_categories', type_='foreignkey')
    op.create_foreign_key('skill_categories_category_id_fkey', 'skill_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('skill_categories_skill_id_fkey', 'skill_categories', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skill_categories_skill_id_fkey', 'skill_categories', type_='foreignkey')
    op.drop_constraint('skill_categories_category_id_fkey', 'skill_categories', type_='foreignkey')
    op.create_foreign_key(op.f('skill_categories_category_id_fkey'), 'skill_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('skill_categories_skill_id_fkey'), 'skill_categories', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###
