"""alter table user_stages

Revision ID: deb9743a9e17
Revises: 3916859fd097
Create Date: 2026-05-11 14:29:25.819894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb9743a9e17'
down_revision: Union[str, Sequence[str], None] = '3916859fd097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stages', sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('user_stages', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stages', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_stages', 'is_accepted')
    # ### end Alembic commands ###
