"""alter meetings fk

Revision ID: e4d9ac19bb28
Revises: f7124cba5435
Create Date: 2026-05-16 12:10:42.167871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d9ac19bb28'
down_revision: Union[str, Sequence[str], None] = 'f7124cba5435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_stage_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('meetings_stage_version_id_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'user_stages', ['user_stage_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meetings', 'stage_version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('stage_version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_stage_version_id_fkey'), 'meetings', 'stage_versions', ['stage_version_id'], ['id'])
    op.drop_column('meetings', 'user_stage_id')
    # ### end Alembic commands ###
