"""alter table meetings 

Revision ID: ec8d70e54c76
Revises: 9b56561e9e08
Create Date: 2026-05-11 02:44:35.719348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8d70e54c76'
down_revision: Union[str, Sequence[str], None] = '9b56561e9e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('stage_version_id', sa.Integer(), nullable=False))
    op.add_column('meetings', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint(op.f('meetings_user_stage_id_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'stage_versions', ['stage_version_id'], ['id'])
    op.drop_column('meetings', 'user_stage_id')
    op.add_column('user_stages', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stages', 'comment')
    op.add_column('meetings', sa.Column('user_stage_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_user_stage_id_fkey'), 'meetings', 'user_stages', ['user_stage_id'], ['id'])
    op.drop_column('meetings', 'description')
    op.drop_column('meetings', 'stage_version_id')
    # ### end Alembic commands ###
