"""add columns ended_at to meetings

Revision ID: f2712f21505a
Revises: 9c641c01ba58
Create Date: 2026-05-30 15:52:25.639649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2712f21505a'
down_revision: Union[str, Sequence[str], None] = '9c641c01ba58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'ended_at')
    # ### end Alembic commands ###
