"""alter level_skills rename col

Revision ID: f7124cba5435
Revises: fc0c16f20e69
Create Date: 2026-05-14 09:55:29.646241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7124cba5435'
down_revision: Union[str, Sequence[str], None] = 'fc0c16f20e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_levels', sa.Column('profile_level_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_levels_profile_level_version_id_fkey'), 'user_levels', type_='foreignkey')
    op.create_foreign_key(None, 'user_levels', 'profile_levels', ['profile_level_id'], ['id'])
    op.drop_column('user_levels', 'profile_level_version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_levels', sa.Column('profile_level_version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.create_foreign_key(op.f('user_levels_profile_level_version_id_fkey'), 'user_levels', 'profile_levels', ['profile_level_version_id'], ['id'])
    op.drop_column('user_levels', 'profile_level_id')
    # ### end Alembic commands ###
