"""alter level_skills

Revision ID: fc0c16f20e69
Revises: 60f750625507
Create Date: 2026-05-14 09:24:13.484130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0c16f20e69'
down_revision: Union[str, Sequence[str], None] = '60f750625507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level_skills', 'profile_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level_skills', 'profile_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
